# Generated by Django 2.2.7 on 2019-11-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0002_auto_20191127_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('summary', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='error.ErrorType')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.Request')),
            ],
        ),
    ]
