# Generated by Django 2.2.7 on 2019-11-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0002_error_type_e404-1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errortype',
            old_name='name',
            new_name='code',
        ),
    ]
