# Generated by Django 2.2.7 on 2019-11-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlugEnding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SlugGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SlugGroupEnding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slug.SlugEnding')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slug.SlugGroup')),
            ],
        ),
    ]
