# Generated by Django 2.2.7 on 2019-11-21 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ajax', models.BooleanField()),
                ('url', models.CharField(max_length=500)),
                ('url_name', models.CharField(max_length=50, null=True)),
                ('user_agent', models.CharField(max_length=500)),
                ('referer', models.CharField(max_length=500, null=True)),
                ('redirect_url', models.CharField(max_length=500, null=True)),
                ('method', models.CharField(choices=[('POST', 'Post'), ('GET', 'Get')], max_length=10)),
                ('ip_addr', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField()),
                ('duration_ms', models.IntegerField(null=True)),
                ('request_size', models.IntegerField()),
                ('response_size', models.IntegerField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('started_at',),
            },
        ),
    ]
