# Generated by Django 2.2.7 on 2019-11-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-started_at',)},
        ),
    ]
