# Generated by Django 2.2.7 on 2019-11-20 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ajax', models.BooleanField()),
                ('url', models.CharField(max_length=500)),
                ('url_name', models.CharField(max_length=50, null=True)),
                ('user_agent', models.CharField(max_length=500)),
                ('referer', models.CharField(max_length=500, null=True)),
                ('redirect_url', models.CharField(max_length=500, null=True)),
                ('method', models.CharField(choices=[('POST', 'Post'), ('GET', 'Get')], max_length=10)),
                ('ip_addr', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField()),
                ('duration_ms', models.IntegerField(null=True)),
                ('request_size', models.IntegerField()),
                ('response_size', models.IntegerField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('started_at',),
            },
        ),
        migrations.CreateModel(
            name='Rev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schema.Request')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RevField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=50)),
                ('field_name', models.CharField(db_index=True, max_length=50)),
                ('field_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('text', 'Text'), ('blob', 'Blob'), ('datetime', 'Datetime')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foreign_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schema.RevField')),
            ],
        ),
        migrations.CreateModel(
            name='RevValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=4000, null=True)),
                ('value_bin', models.BinaryField(null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schema.RevField')),
                ('rev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schema.Rev')),
            ],
        ),
    ]
