# Generated by Django 2.2.7 on 2019-11-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.Request'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
