# Generated by Django 2.2.7 on 2019-11-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_column_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
