# Generated by Django 2.2.7 on 2019-11-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('column', '0005_auto_20191126_1530'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(db_index=True, null=True)),
                ('value_int', models.IntegerField(db_index=True, null=True)),
                ('value_char_250', models.CharField(db_index=True, max_length=250, null=True)),
                ('value_text', models.TextField(null=True)),
                ('value_datetime', models.DateTimeField(db_index=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='column.Column')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Record')),
            ],
        ),
    ]
