# Generated by Django 2.2.7 on 2019-11-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='user',
            new_name='table',
        ),
    ]
