# Generated by Django 2.2.7 on 2019-11-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0002_auto_20191122_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
