# Generated by Django 2.2.7 on 2019-11-23 07:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0003_column_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='column',
            managers=[
                ('obs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='column',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
