# Generated by Django 2.2.7 on 2019-11-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0004_auto_20191123_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='datatype',
            field=models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('char_250', 'Char(250)'), ('text', 'Text'), ('datetime', 'Datetime')], db_index=True, max_length=50),
        ),
    ]
